{{- if .Values.user_service.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: user
data:
  MONGO_URL: {{ .Values.mongo_uri }}
  REDIS_HOST: {{ .Values.redis_host }}
  USER_SERVER_PORT: "{{ .Values.user_port }}"
{{- end }}